#!/usr/bin/env python3
"""Build the L1 team index: which role to call, what it carries, and where to go next.

Why this exists
---------------
The repository already partitions itself correctly: `config/team-manifest.json`
assigns 169 of the 834 physical Skills to 14 top-level roles, and the installer
ships exactly those 169 to the five `canonical-assigned` harness targets
(`bin/installer/catalog.mjs`, `config/cli-adapters.json`). The remaining 665 are
a toolbox that the installer deliberately does not copy.

What was missing was not the partition but a *reader* for it. Every fact needed
to answer "which role do I call, and who can it delegate to?" already lives in
`config/`, but it was spread across one manifest, one hierarchy file and eleven
routing registries - so both agents and humans had to reconstruct the roster by
reading 834 Skill descriptions instead of 14 role cards.

This generator is the missing reader. It emits one document whose layers are
progressively deeper, each ending where the next begins:

    roster table  ->  per-domain role cards  ->  method reverse index
                  ->  starter kits  ->  agent operating rules  ->  toolbox

Generated rather than hand-written on purpose
---------------------------------------------
Every enumerated fact here (roles, triggers, boundaries, method assignments,
delegation targets, leaf counts, kit composition) is a projection of `config/`.
Hand-maintaining such a page guarantees exactly the drift that
`scripts/build_all.sh` and `.githooks/pre-commit` exist to prevent. The prose
this generator does contain is connective only: it carries no counts, because a
count written by hand cannot be checked and would silently rot. Numbers are
always interpolated from the sources, and the wiring asserts (rather than
assumes) that the sources still agree with each other - a new role, a renamed
leaf, or a manager whose routing file disagrees with the hierarchy fails the
build with a message naming the disagreement.

Authority
---------
The output is navigation, never authority. It is registered in
`config/repository-architecture.json` as a `generated-output` of this script so
its lineage is checkable; the authoritative text remains in `config/`.
"""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path

from repository_model import load_manifest, physical_skill_names


OUTPUT_PATH = Path("docs/reference/team-index.md")
GENERATED_MARKER = (
    "<!-- Generated by scripts/build_team_index.py; edit config/team-manifest.json "
    "and config/agent-hierarchy.json instead. -->"
)

# Short domain labels for the roster table. These are the only authored strings
# in an otherwise fully derived document: no generator can compress
# "负责技术战略、架构边界、平台经济性与系统可靠性。" into a scannable column,
# and a wrong label is a human-facing problem rather than a routing one.
# `_domain_labels` fails the build if this map and the manager set diverge, so a
# new C-suite cannot be added without deciding what to call it here.
DOMAIN_LABELS = {
    "ceo": "公司级决策",
    "cto": "技术战略",
    "cpo": "产品",
    "cqo": "量化研究",
    "cmo": "市场增长",
    "cfo": "财务",
    "cdo": "数据",
    "cco": "内容",
    "clo": "法务合规",
    "cro": "研究情报",
    "cso": "销售与客户",
    "coo": "运营",
    "pe": "工程交付",
    "governor": "独立复核",
}

GROUP_TITLES = {
    "coordinator": "协调者（唯一公司级入口）",
    "csuite": "C-suite 域（每个域一个负责人 + 它的叶子专家）",
    "delivery": "交付与复核（不放进任何 C-suite 域）",
}


def _cell(value: str) -> str:
    """Return text that is safe inside a Markdown table cell."""

    return " ".join(str(value).split()).replace("|", "\\|")


def _skill_link(skill_id: str) -> str:
    return "[`{}`](../../skills/{}/)".format(skill_id, skill_id)


def _read_json(root: Path, relative: str) -> dict:
    with (root / relative).open(encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{relative} must contain a JSON object")
    return payload


def _domain_labels(roles: list[str]) -> dict[str, str]:
    missing = sorted(set(roles) - set(DOMAIN_LABELS))
    extra = sorted(set(DOMAIN_LABELS) - set(roles))
    if missing or extra:
        raise ValueError(
            "DOMAIN_LABELS is out of step with the top-level role set "
            f"(missing: {', '.join(missing) or 'none'}; unknown: {', '.join(extra) or 'none'})"
        )
    return DOMAIN_LABELS


class Team:
    """The contract-backed team, plus every derived number the page quotes."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.manifest = load_manifest(root)
        self.hierarchy = _read_json(root, "config/agent-hierarchy.json")
        self.tools = _read_json(root, "config/cli-adapters.json")["tools"]
        self.physical = physical_skill_names(root)

        self.agents = {agent["id"]: agent for agent in self.manifest["agents"]}
        self.order = [agent["id"] for agent in self.manifest["agents"]]
        self.managers = list(self.hierarchy["managers"])
        self.coordinator = self.hierarchy["coordinator"]

        self.labels = _domain_labels(self.order)
        self.registries = self._load_registries()
        self.groups = self._group()
        self.assignments = self._assignments()

    # -- consistency -----------------------------------------------------
    def _load_registries(self) -> dict[str, dict]:
        """Load every routing registry and assert it agrees with the hierarchy.

        The hierarchy says *who* a manager can delegate to; the routing registry
        says *why*. Rendering one without checking the other would let the page
        advertise a leaf that no routing file can justify, or drop one that a
        registry still routes to.
        """

        registries: dict[str, dict] = {}
        for manager_id, settings in self.hierarchy["managers"].items():
            if manager_id not in self.agents:
                raise ValueError(f"hierarchy names an unknown manager: {manager_id}")
            registry = _read_json(self.root, settings["routingFile"])
            if registry["parent"] != manager_id:
                raise ValueError(f"{settings['routingFile']} declares parent {registry['parent']}")
            declared = [item["id"] for item in registry["specialists"]]
            if declared != list(settings["subagents"]):
                raise ValueError(
                    f"{manager_id}: hierarchy subagents and {settings['routingFile']} disagree"
                )
            registries[manager_id] = registry
        return registries

    def _group(self) -> list[tuple[str, list[str]]]:
        """Split the roster into coordinator / C-suite / delivery, in roster order."""

        csuite = [agent_id for agent_id in self.order if agent_id in self.managers]
        delivery = [
            agent_id
            for agent_id in self.order
            if agent_id not in self.managers and agent_id != self.coordinator
        ]
        groups = [
            ("coordinator", [self.coordinator]),
            ("csuite", csuite),
            ("delivery", delivery),
        ]
        flat = [agent_id for _, members in groups for agent_id in members]
        if sorted(flat) != sorted(self.order):
            raise ValueError("roster grouping does not cover every top-level role exactly once")
        return groups

    def _assignments(self) -> dict[str, dict[str, list[str]]]:
        """Resolve each role's method tiers, rejecting references that cannot install."""

        assignments: dict[str, dict[str, list[str]]] = {}
        for agent_id, agent in self.agents.items():
            tiers = agent["skills"]
            if set(tiers) != {"required", "optional", "harnessSpecific", "recommendedExternal"}:
                raise ValueError(f"{agent_id}: unexpected skill tiers {sorted(tiers)}")
            for tier in ("required", "optional", "harnessSpecific"):
                missing = sorted(set(tiers[tier]) - self.physical)
                if missing:
                    raise ValueError(
                        f"{agent_id}.{tier} references Skills with no physical entrypoint: "
                        f"{', '.join(missing)}"
                    )
            assignments[agent_id] = tiers
        return assignments

    # -- derived facts ---------------------------------------------------
    @property
    def assigned_skills(self) -> list[str]:
        assigned = set()
        for tiers in self.assignments.values():
            for tier in ("required", "optional", "harnessSpecific"):
                assigned.update(tiers[tier])
        return sorted(assigned)

    @property
    def canonical_tools(self) -> list[str]:
        return sorted(tool["id"] for tool in self.tools if tool.get("skillSource") == "canonical-assigned")

    def owners_of(self, skill_id: str) -> tuple[list[str], list[str]]:
        """Return (roles that need this method, roles that may reach for it)."""

        required: list[str] = []
        optional: list[str] = []
        for agent_id in self.order:
            tiers = self.assignments[agent_id]
            if skill_id in tiers["required"]:
                required.append(agent_id)
            elif skill_id in tiers["optional"] or skill_id in tiers["harnessSpecific"]:
                optional.append(agent_id)
        return required, optional

    @property
    def leaf_count(self) -> int:
        return sum(len(settings["subagents"]) for settings in self.hierarchy["managers"].values())

    @property
    def harness_only(self) -> set[str]:
        """Methods that only ever appear in a `harnessSpecific` tier."""

        portable: set[str] = set()
        harness: set[str] = set()
        for tiers in self.assignments.values():
            portable.update(tiers["required"])
            portable.update(tiers["optional"])
            harness.update(tiers["harnessSpecific"])
        return harness - portable


def _role_card(team: Team, agent_id: str) -> list[str]:
    """Render one top-level role: what it is for, and who it can delegate to."""

    agent = team.agents[agent_id]
    tiers = team.assignments[agent_id]
    label = team.labels[agent_id]
    outputs = " · ".join(str(item) for item in agent["outputs"])

    lines = [
        # An explicit anchor keeps the roster table's jump links working even
        # though the heading text carries a mentor name and a domain label.
        f'<a id="{agent_id}"></a>',
        "",
        f"### {agent['name']} · {label} · `{agent_id}`",
        "",
        f"**管什么**：{agent['focus']}",
        "",
        f"**✅ 什么时候叫它**：{agent['trigger']}",
        "",
        f"**⛔ 什么时候别叫它**：{agent['doNotUseWhen']}",
        "",
        f"**职责边界**：{agent['boundary']}",
        "",
        f"**标准交付物**：{outputs}",
        "",
    ]

    settings = team.hierarchy["managers"].get(agent_id)
    if settings:
        registry = team.registries[agent_id]
        leaves = registry["specialists"]
        lines.extend(
            [
                f"**规模**：{len(leaves)} 个叶子专家 · "
                f"{len(tiers['required'])} 必需 / {len(tiers['optional'])} 可选 / "
                f"{len(tiers['harnessSpecific'])} Harness 专属",
                "",
                f"**派发约束**：同时最多 {settings['maxConcurrentChildren']} 个子代理；"
                f"角色深度上限 {registry['requiredMaxDepth']}；叶子不得继续派发",
                "",
            ]
        )
        if registry["roleRoutes"]:
            routed = " · ".join(
                f"`{route['id']}`（{route['name']}）" for route in registry["roleRoutes"]
            )
            lines.extend([f"**可调角色**：{routed}", ""])
    else:
        lines.extend(
            [
                f"**规模**：{len(tiers['required'])} 必需 / {len(tiers['optional'])} 可选 / "
                f"{len(tiers['harnessSpecific'])} Harness 专属；不派发子代理",
                "",
            ]
        )

    lines.append(
        f"**直达**：[`agents/{agent_id}/TOOLS.md`](../../agents/{agent_id}/TOOLS.md)"
        "（同一份分配，附来源与评分证据）"
    )
    lines.append("")

    for tier, heading in (
        ("required", "必需方法（core，通用安装器会装）"),
        ("optional", "可选方法（standard 层加入）"),
        ("harnessSpecific", "Harness 专属（依赖特定 harness，通用安装器不装）"),
    ):
        skills = tiers[tier]
        if not skills:
            continue
        lines.append(f"**{heading}**：{' · '.join(_skill_link(skill) for skill in skills)}")
        lines.append("")
    if tiers["recommendedExternal"]:
        external = " · ".join(f"`{skill}`" for skill in tiers["recommendedExternal"])
        lines.append(f"**外部候选（本仓库未打包、未验证，仅供发现）**：{external}")
        lines.append("")

    if settings:
        leaves = team.registries[agent_id]["specialists"]
        lines.extend(
            [
                f"**它能派谁（{len(leaves)} 个叶子）**",
                "",
                "| 叶子专家 | 什么时候叫它 | 什么时候别叫它 |",
                "|---|---|---|",
            ]
        )
        for leaf in leaves:
            lines.append(
                f"| `{_cell(leaf['id'])}` | {_cell(leaf['trigger'])} | {_cell(leaf['doNotUseWhen'])} |"
            )
        lines.append("")
    return lines


def render(team: Team) -> str:
    assigned = team.assigned_skills
    total = len(team.physical)
    toolbox = total - len(assigned)
    canonical = team.canonical_tools
    harness_only = team.harness_only

    lines: list[str] = [
        GENERATED_MARKER,
        "",
        "# 团队精华索引（L1）",
        "",
        "> **一页回答：这个团队能干什么，遇到问题时该叫谁。**",
        ">",
        f"> 全部内容由 `config/` 派生："
        f"[`team-manifest.json`](../../config/team-manifest.json)（{len(team.order)} 个顶层角色）、"
        f"[`agent-hierarchy.json`](../../config/agent-hierarchy.json)（谁管谁）、"
        f"`config/<role>-specialists.json`（{team.leaf_count} 个叶子）。",
        f"> 本页是只读投影，**手改无效**：`npm run check:team-index` 会直接失败。",
        "",
        "## 1 · 精华与工具箱，先分清",
        "",
        "| | 数量 | 会被安装吗 | 读哪一节 |",
        "|---|---|---|---|",
        f"| **团队精华**：已分配给某个角色的 Skill | {len(assigned)} | 会："
        f"{len(canonical)} 个目标声明 `canonical-assigned`（{'、'.join(f'`{tool}`' for tool in canonical)}），"
        f"装的就是这 {len(assigned)} 个 | 第 2、3 节 |",
        f"| **工具箱**：未分配给任何角色的 Skill | {toolbox} | 不会：包里有、安装器不复制 | 第 7 节 · "
        f"[`catalog/`](../../catalog/) |",
        f"| 物理总量（`skills/` 下的可发现入口） | {total} | — | — |",
        "",
        f"**一句话**：`{len(assigned)}` 个方法 + `{len(team.order)}` 个角色 = 精华；"
        f"另外 `{toolbox}` 个不是废料，只是不在任何角色的职责范围内，按需取用即可。",
        "",
        "**怎么读这一页（层层递进，每层结尾指向下一层）**",
        "",
        "| 层 | 你在问什么 | 读哪一节 | 读完你能 |",
        "|---|---|---|---|",
        "| A | 这个团队能干什么、我这个方向归谁 | 第 2 节 总览表 | 按领域锁定一两个候选角色 |",
        "| B | 该不该叫它、它配什么方法、它能派谁 | 第 3 节 角色卡 | 直接点名一个角色，或知道该派谁 |",
        f"| C | 某个方法归谁管 | 第 4 节 方法反查（{len(assigned)}） | 反查到方法及其归属角色 |",
        "| D | 怎么开始动手 | 第 5 节 快速开始 | 选一个 RUNBOOK 跑起来 |",
        "| E | Agent 怎么执行和复核 | 第 6 节 操作规则 | 判级、派发、复核一次做对 |",
        f"| F | 剩下 {toolbox} 个怎么取 | 第 7 节 工具箱 | 知道去哪找、还缺哪条命令 |",
        "",
        "> 本页是**导航**，不是策略权威。路由分级（L0–L3）与各框架强制边界的完整定义在 "
        "[路由分级与强制层](../../docs/guides/routing-and-enforcement.md)；"
        "团队与 Skill 的连接原理在 "
        "[Team/C-suite/Subagent/Skill 连接原理](../../docs/guides/team-agent-skill-architecture.md)。",
        "",
        "## 2 · 团队总览：谁来接你的任务",
        "",
        "这一层只回答「叫什么」。**为什么不该叫它、它配了哪些方法、能派谁**，在下一层的角色卡里。",
        "",
        "| 角色 | 领域 | 什么时候叫它 | 叶子 | 方法 |",
        "|---|---|---|---|---|",
    ]

    for agent_id in team.order:
        agent = team.agents[agent_id]
        settings = team.hierarchy["managers"].get(agent_id)
        leaves = len(settings["subagents"]) if settings else 0
        tiers = team.assignments[agent_id]
        method_count = len(set(tiers["required"] + tiers["optional"] + tiers["harnessSpecific"]))
        lines.append(
            f"| [`{agent_id}`](#{agent_id}) | {_cell(team.labels[agent_id])} | "
            f"{_cell(agent['trigger'])} | "
            f"{leaves or '—'} | {method_count} |"
        )
    lines.extend(
        [
            "",
            f"共 {len(team.order)} 个角色、{team.leaf_count} 个叶子、{len(assigned)} 个方法。"
            "叶子只在第 3 节展开 —— 先从这 14 行里挑人，挑不出再往下看。",
            "",
            "## 3 · 角色卡：每个人管什么、配什么方法、能派谁",
            "",
        ]
    )

    for group, members in team.groups:
        lines.extend([f"### {GROUP_TITLES[group]}", ""])
        for agent_id in members:
            lines.extend(_role_card(team, agent_id))

    lines.extend(
        [
            "## 4 · 方法反查：某个 Skill 归谁管",
            "",
            f"安装的是 {len(assigned)} 个「已分配」方法。要按方法名反查归属，看这张表：",
            "「必需」= 该角色的核心方法（缺失即失职）；「可选 / Harness」= 该角色可以调用，但不是它的身份。",
            "",
            "| Skill | 必需（谁的核心方法） | 可选 / Harness |",
            "|---|---|---|",
        ]
    )
    for skill in assigned:
        required, optional = team.owners_of(skill)
        mark = " ⚡" if skill in harness_only else ""
        lines.append(
            f"| {_skill_link(skill)}{mark} | "
            f"{'、'.join(f'`{agent_id}`' for agent_id in required) or '—'} | "
            f"{'、'.join(f'`{agent_id}`' for agent_id in optional) or '—'} |"
        )
    if harness_only:
        lines.extend(
            [
                "",
                "⚡ = 只出现在 Harness 专属层：需要对应 harness 或外部连接器，通用安装器不会复制。",
                "本表合并了「可选」与「Harness 专属」；某个角色到底在哪一层，看第 3 节它自己的卡片。",
            ]
        )

    kits = team.manifest["kits"]
    lines.extend(
        [
            "",
            f"## 5 · 快速开始：{len(kits)} 条已经编排好的路径",
            "",
            "不确定该组什么团队时，别自己拼 —— 下面的 Kit 已经把角色、产出、复核和验收都编排好了。"
            "每个 Kit 的入口是一份 RUNBOOK。",
            "",
            "| Kit | 拿到什么产出 | 协调者 | 参与角色 | 强制复核 | RUNBOOK |",
            "|---|---|---|---|---|---|",
        ]
    )
    for kit in kits:
        entry = f"[`{kit['entrypoint']}`](../../{kit['entrypoint']})"
        lines.append(
            f"| **{kit['name']}**（`{kit['id']}`） | {_cell(kit['outcome'])} | "
            f"`{kit['coordinator']}` | "
            f"{'、'.join(f'`{agent_id}`' for agent_id in kit['agents'])} | "
            f"{'、'.join(f'`{agent_id}`' for agent_id in kit['reviewers']) or '—'} | {entry} |"
        )

    policy = team.hierarchy["executionPolicy"]
    depth = team.hierarchy["requiredMaxDepth"]
    threads = team.hierarchy["recommendedMaxThreads"]
    lines.extend(
        [
            "",
            "## 6 · Agent 操作规则",
            "",
            "给 Agent 的四步，全部可机器判定：",
            "",
            "1. **判级**。先问三个问题：只涉及一个 C-suite 域吗？需要跨职能取舍吗？"
            "结果要对外声明发布 / 资金 / 法律 / 安全 / 完成吗？"
            "单域直接找该域负责人；跨职能才上 "
            f"`{team.coordinator}`；一旦涉及对外声明，必须追加 `governor` 独立复核。",
            "2. **选最小充分团队**。用第 2 节的总览表按 `trigger` 命中，不要为了「周全」把角色叫满。",
            "3. **派发**。本团队的硬约束来自契约，不是建议："
            f"协调者是 `{team.coordinator}`；角色深度上限 {depth}；"
            f"建议并发线程 {threads}；执行策略 `{policy}`；"
            f"每个 C-suite 域同时最多 2 个子代理；"
            f"**叶子专家不得继续派发**（它们没有 Agent 工具）。"
            "叶子遇到需要再拆的任务，向所属 C-suite 上抛。",
            "4. **交证据**。派发时必须给：目标、边界（不做什么）、验收标准、证据要求。"
            "结论要能追溯到具体文件、命令输出或数据源。",
            "",
            "判级与强制边界的完整定义见 "
            "[路由分级与强制层](../../docs/guides/routing-and-enforcement.md)；"
            "各框架能强制什么、不能强制什么见 "
            "[框架兼容性](../../docs/guides/harness-compatibility.html)。",
            "",
            "## 7 · 工具箱：没装的那 "
            f"{toolbox} 个",
            "",
            f"`skills/` 下有 {total} 个物理入口，其中 {len(assigned)} 个属于团队（第 3、4 节），"
            f"剩下 {toolbox} 个不属于任何角色，安装器不会复制。它们仍然可以：",
            "",
            "- **检索**：看生成目录 [`catalog/README.md`](../../catalog/README.md) 或机器可读的 "
            "[`catalog/skill-index.json`](../../catalog/skill-index.json)。",
            "- **取用**：目录是完整的。npm 安装的包里有整棵 `skills/` 树"
            "（`node_modules/agi-super-team/skills/<id>/`，[ADR-0008](../../docs/adr/"
            "0008-ship-complete-skills-directory.md) 决定全量打包）；git 用户直接在 "
            "`skills/<id>/` 下拿。要取就取整个目录 —— 只拿 `SKILL.md` 会得到一个坏 Skill，"
            "因为它的正文会引用自己的 `references/` 与 `scripts/`。",
            "- **还缺什么**：目前没有针对单个 Skill 的获取命令，也没有把工具箱排除出包的开关。"
            "方案取舍与待决策项在 "
            "[按需获取提案](../../docs/optimization/2026-09-23-l2-on-demand-skill-delivery.md)。",
            "",
            "---",
            "",
            "本页由 [`scripts/build_team_index.py`](../../scripts/build_team_index.py) 生成，"
            "登记在 [`config/repository-architecture.json`](../../config/repository-architecture.json)。",
            "验证：`npm run check:team-index`（或 `npm run build:team-index` 重新生成）。",
            f"派生自 {len(team.order)} 个角色、{team.leaf_count} 个叶子专家的契约；"
            "权威源永远是 `config/`，本页只是它的投影。",
            "",
        ]
    )
    return "\n".join(lines)


def build_outputs(root: Path) -> dict[Path, str]:
    return {root / OUTPUT_PATH: render(Team(root))}


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = build_outputs(root)

    stale = [
        path
        for path, content in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    if arguments.check:
        if stale:
            for path in stale:
                print(f"Team index is stale: {path.relative_to(root)}")
            return 1
        print(f"Team index is current: {len(outputs)}")
        return 0

    for path in stale:
        _atomic_write(path, outputs[path])
        print(f"Wrote {path.relative_to(root)}")
    if not stale:
        print(f"Team index already current: {len(outputs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
